<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Badgernet.Umbraco.MediaTools</PackageId>
    <Version>18.0.0</Version>

    <Description>This package adds additional functionalities to Umbraco media section.
    </Description>

    <PackageProjectUrl>https://github.com/Fric-88/Badgernet.Umbraco.MediaTools</PackageProjectUrl> 
    <RepositoryUrl>https://github.com/Fric-88/Badgernet.Umbraco.MediaTools</RepositoryUrl> 
    <Authors>David Jazbec</Authors>
    <PackageReadmeFile>README.md</PackageReadmeFile> 
    <PackageIcon>logo.png</PackageIcon> 
    <PackageTags>umbraco-marketplace</PackageTags> 
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile> 
    <PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance> 
    <PackageReleaseNotes>Umbraco 18 compatible.</PackageReleaseNotes> 

  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE.txt" Pack="true" PackagePath="" />
    <None Include="..\logo.png" Pack="true" PackagePath="" />
    <None Include="..\README.md" Pack="true" PackagePath="" /> 
  </ItemGroup>

  <ItemGroup>
    <Content Remove="**\tsconfig.json" />
    <Content Remove="**\package.json" />
    <Content Remove="**\package-lock.json" />
    <Content Remove="**\vite.config.*" />
    <Content Remove="wwwroot\**\*.ts" />

    <None Include="tsconfig.json;package.json;vite.config.*" Pack="false" />
  </ItemGroup>

  <PropertyGroup>
    <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.OpenApi.Generated</InterceptorsNamespaces>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Umbraco.Cms" Version="[18.0.0, 19.0.0)" />
  </ItemGroup>

  <ItemGroup>
    <ClCompile Include="assets\src\elements\imageEditor\wasm\manipulate.cpp" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="assets\public\wasm\" />
  </ItemGroup>

</Project>
