// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from './client';
import type { DownloadMediaData, DownloadMediaResponses, GetMediaFoldersData, GetMediaFoldersResponses, GetMediaInfoData, GetMediaInfoResponses, GetMediaInfoErrors, GetMetadataData, GetMetadataResponses, ProcessImagesData, ProcessImagesResponses, ProcessImagesErrors, RenameMediaData, RenameMediaResponses, RenameMediaErrors, ReplaceImageData, ReplaceImageResponses, ReplaceImageErrors, SearchMediaData, SearchMediaResponses, TrashMediaData, TrashMediaResponses, GetSettingsData, GetSettingsResponses, SetSettingsData, SetSettingsResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const downloadMedia = <ThrowOnError extends boolean = false>(options?: Options<DownloadMediaData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<DownloadMediaResponses, unknown, ThrowOnError>({
        url: '/gallery/download-media',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getMediaFolders = <ThrowOnError extends boolean = false>(options?: Options<GetMediaFoldersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMediaFoldersResponses, unknown, ThrowOnError>({
        url: '/gallery/get-media-folders',
        ...options
    });
};

export const getMediaInfo = <ThrowOnError extends boolean = false>(options?: Options<GetMediaInfoData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMediaInfoResponses, GetMediaInfoErrors, ThrowOnError>({
        url: '/gallery/get-media-info',
        ...options
    });
};

export const getMetadata = <ThrowOnError extends boolean = false>(options?: Options<GetMetadataData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMetadataResponses, unknown, ThrowOnError>({
        url: '/gallery/get-metadata',
        ...options
    });
};

export const processImages = <ThrowOnError extends boolean = false>(options?: Options<ProcessImagesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<ProcessImagesResponses, ProcessImagesErrors, ThrowOnError>({
        url: '/gallery/process-images',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const renameMedia = <ThrowOnError extends boolean = false>(options?: Options<RenameMediaData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<RenameMediaResponses, RenameMediaErrors, ThrowOnError>({
        url: '/gallery/rename-media',
        ...options
    });
};

export const replaceImage = <ThrowOnError extends boolean = false>(options?: Options<ReplaceImageData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<ReplaceImageResponses, ReplaceImageErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/gallery/replace-image',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

export const searchMedia = <ThrowOnError extends boolean = false>(options?: Options<SearchMediaData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<SearchMediaResponses, unknown, ThrowOnError>({
        url: '/gallery/search-media',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const trashMedia = <ThrowOnError extends boolean = false>(options?: Options<TrashMediaData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<TrashMediaResponses, unknown, ThrowOnError>({
        url: '/gallery/trash-media',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getSettings = <ThrowOnError extends boolean = false>(options?: Options<GetSettingsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetSettingsResponses, unknown, ThrowOnError>({
        url: '/settings/get-settings',
        ...options
    });
};

export const setSettings = <ThrowOnError extends boolean = false>(options?: Options<SetSettingsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<SetSettingsResponses, unknown, ThrowOnError>({
        url: '/settings/set-settings',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};