// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { DownloadMediaData, DownloadMediaResponses, GetMediaFoldersData, GetMediaFoldersResponses, GetMediaInfoData, GetMediaInfoErrors, GetMediaInfoResponses, GetMetadataData, GetMetadataResponses, GetSettingsData, GetSettingsResponses, ProcessImagesData, ProcessImagesErrors, ProcessImagesResponses, RenameMediaData, RenameMediaErrors, RenameMediaResponses, ReplaceImageData, ReplaceImageErrors, ReplaceImageResponses, SearchMediaData, SearchMediaResponses, SetSettingsData, SetSettingsResponses, TrashMediaData, TrashMediaResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const downloadMedia = <ThrowOnError extends boolean = false>(options?: Options<DownloadMediaData, ThrowOnError>): RequestResult<DownloadMediaResponses, unknown, ThrowOnError> => (options?.client ?? client).post<DownloadMediaResponses, unknown, ThrowOnError>({
    url: '/gallery/download-media',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const getMediaFolders = <ThrowOnError extends boolean = false>(options?: Options<GetMediaFoldersData, ThrowOnError>): RequestResult<GetMediaFoldersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetMediaFoldersResponses, unknown, ThrowOnError>({ url: '/gallery/get-media-folders', ...options });

export const getMediaInfo = <ThrowOnError extends boolean = false>(options?: Options<GetMediaInfoData, ThrowOnError>): RequestResult<GetMediaInfoResponses, GetMediaInfoErrors, ThrowOnError> => (options?.client ?? client).get<GetMediaInfoResponses, GetMediaInfoErrors, ThrowOnError>({ url: '/gallery/get-media-info', ...options });

export const getMetadata = <ThrowOnError extends boolean = false>(options?: Options<GetMetadataData, ThrowOnError>): RequestResult<GetMetadataResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetMetadataResponses, unknown, ThrowOnError>({ url: '/gallery/get-metadata', ...options });

export const processImages = <ThrowOnError extends boolean = false>(options?: Options<ProcessImagesData, ThrowOnError>): RequestResult<ProcessImagesResponses, ProcessImagesErrors, ThrowOnError> => (options?.client ?? client).post<ProcessImagesResponses, ProcessImagesErrors, ThrowOnError>({
    url: '/gallery/process-images',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const renameMedia = <ThrowOnError extends boolean = false>(options?: Options<RenameMediaData, ThrowOnError>): RequestResult<RenameMediaResponses, RenameMediaErrors, ThrowOnError> => (options?.client ?? client).post<RenameMediaResponses, RenameMediaErrors, ThrowOnError>({ url: '/gallery/rename-media', ...options });

export const replaceImage = <ThrowOnError extends boolean = false>(options?: Options<ReplaceImageData, ThrowOnError>): RequestResult<ReplaceImageResponses, ReplaceImageErrors, ThrowOnError> => (options?.client ?? client).post<ReplaceImageResponses, ReplaceImageErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/gallery/replace-image',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});

export const searchMedia = <ThrowOnError extends boolean = false>(options?: Options<SearchMediaData, ThrowOnError>): RequestResult<SearchMediaResponses, unknown, ThrowOnError> => (options?.client ?? client).post<SearchMediaResponses, unknown, ThrowOnError>({
    url: '/gallery/search-media',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const trashMedia = <ThrowOnError extends boolean = false>(options?: Options<TrashMediaData, ThrowOnError>): RequestResult<TrashMediaResponses, unknown, ThrowOnError> => (options?.client ?? client).post<TrashMediaResponses, unknown, ThrowOnError>({
    url: '/gallery/trash-media',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const getSettings = <ThrowOnError extends boolean = false>(options?: Options<GetSettingsData, ThrowOnError>): RequestResult<GetSettingsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetSettingsResponses, unknown, ThrowOnError>({ url: '/settings/get-settings', ...options });

export const setSettings = <ThrowOnError extends boolean = false>(options?: Options<SetSettingsData, ThrowOnError>): RequestResult<SetSettingsResponses, unknown, ThrowOnError> => (options?.client ?? client).post<SetSettingsResponses, unknown, ThrowOnError>({
    url: '/settings/set-settings',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});
