// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { DownloadMediaData, DownloadMediaResponse, GetMediaFoldersResponse, GetMediaInfoData, GetMediaInfoResponse, GetMetadataData, GetMetadataResponse, ProcessImagesData, ProcessImagesResponse, RenameMediaData, RenameMediaResponse, ReplaceImageData, ReplaceImageResponse, SearchMediaData, SearchMediaResponse, TrashMediaData, TrashMediaResponse, GetSettingsData, GetSettingsResponse, SetSettingsData, SetSettingsResponse } from './types.gen';

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const downloadMedia = (data: DownloadMediaData = {}): CancelablePromise<DownloadMediaResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/gallery/download-media',
    body: data.requestBody,
    mediaType: 'application/json'
}); };

/**
 * @returns unknown OK
 * @throws ApiError
 */
export const getMediaFolders = (): CancelablePromise<GetMediaFoldersResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/gallery/get-media-folders'
}); };

/**
 * @param data The data for the request.
 * @param data.mediaId
 * @returns unknown OK
 * @throws ApiError
 */
export const getMediaInfo = (data: GetMediaInfoData = {}): CancelablePromise<GetMediaInfoResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/gallery/get-media-info',
    query: {
        mediaId: data.mediaId
    },
    errors: {
        400: 'Bad Request'
    }
}); };

/**
 * @param data The data for the request.
 * @param data.id
 * @returns unknown OK
 * @throws ApiError
 */
export const getMetadata = (data: GetMetadataData = {}): CancelablePromise<GetMetadataResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/gallery/get-metadata',
    query: {
        id: data.id
    }
}); };

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const processImages = (data: ProcessImagesData = {}): CancelablePromise<ProcessImagesResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/gallery/process-images',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        400: 'Bad Request'
    }
}); };

/**
 * @param data The data for the request.
 * @param data.mediaId
 * @param data.newName
 * @returns unknown OK
 * @throws ApiError
 */
export const renameMedia = (data: RenameMediaData = {}): CancelablePromise<RenameMediaResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/gallery/rename-media',
    query: {
        mediaId: data.mediaId,
        newName: data.newName
    },
    errors: {
        400: 'Bad Request'
    }
}); };

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.saveAs
 * @param data.formData
 * @returns unknown OK
 * @throws ApiError
 */
export const replaceImage = (data: ReplaceImageData = {}): CancelablePromise<ReplaceImageResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/gallery/replace-image',
    query: {
        id: data.id,
        saveAs: data.saveAs
    },
    formData: data.formData,
    mediaType: 'multipart/form-data',
    errors: {
        400: 'Bad Request'
    }
}); };

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const searchMedia = (data: SearchMediaData = {}): CancelablePromise<SearchMediaResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/gallery/search-media',
    body: data.requestBody,
    mediaType: 'application/json'
}); };

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const trashMedia = (data: TrashMediaData = {}): CancelablePromise<TrashMediaResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/gallery/trash-media',
    body: data.requestBody,
    mediaType: 'application/json'
}); };

/**
 * @param data The data for the request.
 * @param data.userKey
 * @returns unknown OK
 * @throws ApiError
 */
export const getSettings = (data: GetSettingsData = {}): CancelablePromise<GetSettingsResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/settings/get-settings',
    query: {
        userKey: data.userKey
    }
}); };

/**
 * @param data The data for the request.
 * @param data.userKey
 * @param data.requestBody
 * @returns string OK
 * @throws ApiError
 */
export const setSettings = (data: SetSettingsData = {}): CancelablePromise<SetSettingsResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/settings/set-settings',
    query: {
        userKey: data.userKey
    },
    body: data.requestBody,
    mediaType: 'application/json',
    responseHeader: 'Umb-Notifications'
}); };