// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:2812' | (string & {});
};

export type ConvertMode = 'Lossy' | 'Lossless';

export type ConverterSettings = {
    enabled: boolean;
    convertMode: ConvertMode;
    convertQuality: number;
};

export type FilterImagesDto = {
    folderName?: string | null;
    width: number;
    height: number;
    nameLike: string;
    extensionLike: string;
    sizeFilter: SizeFilter;
};

export type GeneralSettings = {
    keepOriginals: boolean;
    ignoreKeyword: string;
};

export type ImageMediaDto = {
    id: number;
    name: string;
    width: number;
    height: number;
    extension: string;
    path: string;
    size: string;
};

export type ImageMetadataDto = {
    verticalResolution: number;
    horizontalResolution: number;
    decodedImageFormat: string;
    resolutionUnits: string;
    exifTags: Array<ParsedTag>;
    iptcTags: Array<ParsedTag>;
    xmpProfile: string;
};

export type MediaFolderDto = {
    key: string;
    name: string;
    path: string;
};

export type MetadataRemoverSettings = {
    enabled: boolean;
    removeDateTime: boolean;
    removeCameraInfo: boolean;
    removeGpsInfo: boolean;
    removeShootingSituationInfo: boolean;
    removeXmpProfile: boolean;
    removeIptcProfile: boolean;
    metadataTagsToRemove: Array<string>;
};

export type OperationResponse = {
    status: ResponseStatus;
    message: string;
    payload?: unknown;
};

export type ParsedTag = {
    tag: string;
    value: string;
};

export type ProcessImagesDto = {
    ids: Array<number>;
    resize: boolean;
    convert: boolean;
    resizeMode: ResizeMode;
    width: number;
    height: number;
    convertMode: ConvertMode;
    convertQuality: number;
};

export type ResizeMode = 'FitInside' | 'ExactSize';

export type ResizerFolderOverride = {
    key: string;
    targetWidth: number;
    targetHeight: number;
    resizerEnabled: boolean;
};

export type ResizerSettings = {
    enabled: boolean;
    ignoreAspectRatio: boolean;
    targetWidth: number;
    targetHeight: number;
    folderOverrides: Array<ResizerFolderOverride>;
};

export type ResponseStatus = 'Success' | 'Error' | 'Skipped' | 'Warning';

export type SizeFilter = 'AllSizes' | 'BiggerThan' | 'SmallerThan';

export type UserSettingsDto = {
    resizer: ResizerSettings;
    converter: ConverterSettings;
    metadataRemover: MetadataRemoverSettings;
    general: GeneralSettings;
};

export type DownloadMediaData = {
    body?: Array<number>;
    path?: never;
    query?: never;
    url: '/gallery/download-media';
};

export type DownloadMediaResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type DownloadMediaResponse = DownloadMediaResponses[keyof DownloadMediaResponses];

export type GetMediaFoldersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/gallery/get-media-folders';
};

export type GetMediaFoldersResponses = {
    /**
     * OK
     */
    200: Array<MediaFolderDto>;
};

export type GetMediaFoldersResponse = GetMediaFoldersResponses[keyof GetMediaFoldersResponses];

export type GetMediaInfoData = {
    body?: never;
    path?: never;
    query?: {
        mediaId?: number;
    };
    url: '/gallery/get-media-info';
};

export type GetMediaInfoErrors = {
    /**
     * Bad Request
     */
    400: ImageMediaDto;
};

export type GetMediaInfoError = GetMediaInfoErrors[keyof GetMediaInfoErrors];

export type GetMediaInfoResponses = {
    /**
     * OK
     */
    200: ImageMediaDto;
};

export type GetMediaInfoResponse = GetMediaInfoResponses[keyof GetMediaInfoResponses];

export type GetMetadataData = {
    body?: never;
    path?: never;
    query?: {
        id?: number;
    };
    url: '/gallery/get-metadata';
};

export type GetMetadataResponses = {
    /**
     * OK
     */
    200: ImageMetadataDto;
};

export type GetMetadataResponse = GetMetadataResponses[keyof GetMetadataResponses];

export type ProcessImagesData = {
    body?: ProcessImagesDto;
    path?: never;
    query?: never;
    url: '/gallery/process-images';
};

export type ProcessImagesErrors = {
    /**
     * Bad Request
     */
    400: OperationResponse;
};

export type ProcessImagesError = ProcessImagesErrors[keyof ProcessImagesErrors];

export type ProcessImagesResponses = {
    /**
     * OK
     */
    200: OperationResponse;
};

export type ProcessImagesResponse = ProcessImagesResponses[keyof ProcessImagesResponses];

export type RenameMediaData = {
    body?: never;
    path?: never;
    query?: {
        mediaId?: number;
        newName?: string;
    };
    url: '/gallery/rename-media';
};

export type RenameMediaErrors = {
    /**
     * Bad Request
     */
    400: OperationResponse;
};

export type RenameMediaError = RenameMediaErrors[keyof RenameMediaErrors];

export type RenameMediaResponses = {
    /**
     * OK
     */
    200: OperationResponse;
};

export type RenameMediaResponse = RenameMediaResponses[keyof RenameMediaResponses];

export type ReplaceImageData = {
    body?: {
        imageFile?: Blob | File;
    };
    path?: never;
    query?: {
        id?: number;
        saveAs?: string;
    };
    url: '/gallery/replace-image';
};

export type ReplaceImageErrors = {
    /**
     * Bad Request
     */
    400: OperationResponse;
};

export type ReplaceImageError = ReplaceImageErrors[keyof ReplaceImageErrors];

export type ReplaceImageResponses = {
    /**
     * OK
     */
    200: OperationResponse;
};

export type ReplaceImageResponse = ReplaceImageResponses[keyof ReplaceImageResponses];

export type SearchMediaData = {
    body?: FilterImagesDto;
    path?: never;
    query?: never;
    url: '/gallery/search-media';
};

export type SearchMediaResponses = {
    /**
     * OK
     */
    200: Array<ImageMediaDto>;
};

export type SearchMediaResponse = SearchMediaResponses[keyof SearchMediaResponses];

export type TrashMediaData = {
    body?: Array<number>;
    path?: never;
    query?: never;
    url: '/gallery/trash-media';
};

export type TrashMediaResponses = {
    /**
     * OK
     */
    200: OperationResponse;
};

export type TrashMediaResponse = TrashMediaResponses[keyof TrashMediaResponses];

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: {
        userKey?: string;
    };
    url: '/settings/get-settings';
};

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: UserSettingsDto;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type SetSettingsData = {
    body?: UserSettingsDto;
    path?: never;
    query?: {
        userKey?: string;
    };
    url: '/settings/set-settings';
};

export type SetSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};
